name: Documentation Issue
description: Did we miss something in the documentation? Report them here.
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: "# Documentation Report"
  - type: dropdown
    attributes:
      label: "Cause of the issue"
      description: "What caused you to report this issue?"
      multiple: false
      options:
        - "Missing game information or instruction"
        - "Typos"
        - "Confusing explanation"
        - "Others"
  - type: textarea
    attributes:
      label: "Describe your issue"
      description: "What seems to be the issue?"
      placeholder: "Describe your issue..."
  - type: markdown
    attributes:
      value: "## Possible solution(s)"
  - type: dropdown
    attributes:
      label: "How can we fix this?"
      description: "What are you looking for to resolve this issue?"
      multiple: true
      options:
        - "I can help or fix the issue by myself"
        - "I am waiting for the community's explanation"
        - "I am waiting for the developer(s) to help"
        - "I am waiting for HoYoverse to fix the issue"
        - "Others (please specify in additional notes)"
  - type: textarea
    id: remarks
    attributes:
      label: Additional notes and remarks
      description: Do you have any other notes or remarks you want to add?
      placeholder: "Please give us any other additional information that could speed up the process. "
  - type: checkboxes
    attributes:
      label: "Preflight Checklist"
      description: "Select one or more solution(s)"
      options:
        - label: "I understand that this is not a feature request or enhancement request. Requests can be made in the Discussions tab."
          required: true
        - label: "I understand that this is not a question, a crash report, an error report, or a bug report. Bug reports can be reported in Issues > Bug Report."
          required: true
        - label: "I am available for further questions."
          required: false
        - label: "I can help with documentation."
          required: false
        - label: "I understand the scanner's codebase."
          required: false
        - label: "I have checked the Issues tab and Discussions tab, and there are none similar to mine."
          required: true
