name: Documentation Issue
description: We missed something in the documentation? Starts here.
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: "# Documentation Report"
  - type: dropdown
    attributes:
      label: "Cause of the issue"
      description: "What caused you to report this issue?"
      multiple: false
      options:
        - "Missing game information or instruction"
        - "Typos"
        - "Confusing explaination"
        - "Other"
  - type: textarea
    attributes:
      label: "Describe your issue"
      description: "What seems to be the issue?"
      placeholder: "Describe your issue..."
  - type: markdown
    attributes:
      value: "## Possible solutions"
  - type: dropdown
    attributes:
      label: "How can we fix this?"
      description: "What are you looking for to resolve this issue?"
      multiple: true
      options:
        - "I can help/fix by myself"
        - "Waiting for community's explaination"
        - "Waiting for scanner developer's help"
        - "Waiting for HoYoverse to fix the issue"
        - "Other (please specify in additional notes)"
  - type: textarea
    id: remarks
    attributes:
      label: Additional notes and remarks
      description: Do you have any other notes or remarks you want to add?
      placeholder: "Please give us some additional information that you seem fit and could speed up our process. "
  - type: checkboxes
    attributes:
      label: "Preflight Checklist"
      description: "Select one or more solutions"
      options:
        - label: "I understands that this is not a feature request or enhancement request. That will be done in Discussions tab."
          required: true
        - label: "I understands that this is not a question, crash report, error report, or a bug report. That will be done in Issues > Bug Report."
          required: true
        - label: "I am available for further questions."
          required: false
        - label: "I can help with documentation."
          required: false
        - label: "I understand the scanner's codebase."
          required: false
        - label: "I have checked the Issues tab and Discussions tab, and there is none similar to mine."
          required: true
